sonar.projectKey=Mif10-G14-projet-transversal-2026_API-AtlaxOasis-2026_AZ0gI1mtpItf3KCWeG9N
sonar.qualitygate.wait=true

sonar.sources=src
sonar.tests=tests

sonar.python.version=3
sonar.python.coverage.reportPaths=coverage.xml